# Generated by Django 5.1.13 on 2025-11-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='quiz_mode',
            field=models.CharField(choices=[('random', 'Random Mode'), ('practice_all', 'Practice All Mode')], default='random', max_length=20),
        ),
    ]
