# Generated by Django 5.1.13 on 2025-11-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizattempt_quiz_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken',
            field=models.IntegerField(blank=True, help_text='Time taken in seconds (only for random mode)', null=True),
        ),
    ]
