# Generated by Django 5.1.13 on 2025-11-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
