# Generated by Django 5.1.13 on 2025-11-13 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0002_question_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('title', models.CharField(blank=True, help_text="Unit title (e.g., 'Introduction to Programming')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the unit')),
                ('topics', models.TextField(blank=True, help_text='List of topics covered in this unit (one per line or comma-separated)')),
                ('syllabus_pdf', models.FileField(blank=True, help_text='Upload syllabus PDF for this subject', null=True, upload_to='syllabus_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='semesters.subject')),
            ],
            options={
                'ordering': ['subject', 'unit_number'],
                'unique_together': {('subject', 'unit_number')},
            },
        ),
    ]
