# Generated by Django 5.1.13 on 2025-11-14 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0003_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField()),
                ('question_text', models.TextField(help_text='Programming question with proper Python indentation')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('added_by', models.CharField(blank=True, max_length=100)),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_questions', to='semesters.subject')),
            ],
            options={
                'ordering': ['subject', 'unit', 'created_at'],
            },
        ),
    ]
