# Generated by Django 5.1.13 on 2025-11-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0004_programmingquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingquestion',
            name='solution',
            field=models.TextField(blank=True, help_text="Solution(s) for the question. Separate multiple solutions with '|||OPTION|||' (max 3 options)", null=True),
        ),
    ]
