# Generated by Django 5.1.13 on 2025-12-01 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0005_programmingquestion_solution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingQuestionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField()),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_accesses', to='semesters.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_question_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programming Question Access',
                'verbose_name_plural': 'Programming Question Accesses',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['user', 'subject', 'unit'], name='semesters_p_user_id_c58500_idx'), models.Index(fields=['-accessed_at'], name='semesters_p_accesse_7d55f4_idx')],
            },
        ),
    ]
